django11python3/src/djangofypproject/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token

from django.conf.urls import url, include

from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, LogoutView

from profiles.views import RegisterView
# from recognition.views import detect


urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# urlpatterns += [
#     url(r'^api/facescan/', include('facescan.api.urls', namespace='api-facescan')),
#     # url(r'^api-token-auth/', obtain_jwt_token),
#     # url(r'^api-token-refresh/', refresh_jwt_token),
#     # url(r'^api-token-verify/', verify_jwt_token),
# ]

urlpatterns += [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^recognition/', include('recognition.urls', namespace='recognition')),
    # url(r'^recognition/detect/$', 'recognition.views.detect'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('facescan.urls', namespace='facescan')),
    url(r'^contact/', include('menu.urls', namespace='menu')),
    url(r'^myprofile/$', TemplateView.as_view(template_name='myprofile.html'), name='myprofile'),
    # url(r'^recognition/$', TemplateView.as_view(template_name='recognition.html'), name='recognition'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django11python3/src/facescan/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    ItemListView,
    ItemCreateView,
    ItemDetailView,
    ItemUpdateView,

)


urlpatterns = [
    url(r'create/$', ItemCreateView.as_view(), name='create'),
    # url(r'(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'(?P<slug>[\w-]+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django11python3/src/menu/urls.py
from django.conf.urls import url


from menu.views import (
    ContactListView,
    ContactDetailView,
    ContactCreateView,
    ContactUpdateView,

)


urlpatterns = [
    url(r'create/$', ContactCreateView.as_view(), name='create'),
    # url(r'(?P<slug>[\w-]+)/edit/$', ContactUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', ContactUpdateView.as_view(), name='detail'),
    url(r'^$', ContactListView.as_view(), name='list'),
]

django11python3/src/profiles/urls.py
from .views import ProfileDetailView# , RandomProfileDetailView
from django.conf.urls import url


urlpatterns = [
    # url(r'^random/$', RandomProfileDetailView.as_view(), name='random'),
    url(r'^(?P<username>[\w-]+)/$', ProfileDetailView.as_view(), name='detail'),
]

django11python3/src/recognition/urls.py
from django.conf.urls import url
from recognition import views

urlpatterns = [
    url(r'^detect/$', views.detect, name='detect'),
    url(r'^train/$', views.train, name='train'),
    # url(r'^$', image_create, name='create'),
    # url(r'^(?P<slug>[\w-]+)/$', ImageDetailView.as_view(), name='detail'),
]

django11python3/src/facescan/forms.py
from django import forms
from .models import Item

from menu.models import ContactDetails


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'contact',
            'contents',
            'excludes',
            'image',
            'public'

        ]

    def __init__(self, user=None, *args, **kwargs):
        print(user)
        # print(kwargs.pop('instants'))
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['contact'].queryset = ContactDetails.objects.filter(owner=user)

django11python3/src/menu/forms.py
from django import forms

from .models import ContactDetails


class ContactCreateForm(forms.Form):
    name            = forms.CharField()
    relationship    = forms.CharField()

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name=="Hello":
            raise forms.ValidationError("Not a valid name")
        return name


class ContactImageCreateForm(forms.ModelForm):
    class Meta:
        model = ContactDetails
        fields = [
            'name',
            'relationship',
            'slug',
        ]

    # custom validation
    def clean_name(self):
        name = self.cleaned_data.get("name")
        if name=="hey":
            raise forms.ValidationError("Not a valid name")
        return name

    # def clean_number(self):
    #     number = self.cleaned_data.get("number")
    #     if ".edu" in number:
    #         raise forms.ValidationError("It is not a valid number")
    #     return number

django11python3/src/profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        # create a new user hash for activating email.

        if commit:
            user.save()
            # user.profile.send_activation_email()

        return user

django11python3/src/facescan/templates/facescan/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Images Detail | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
    {% if form.instance.image %}
        <img src='{{ form.instance.image.url }}' class='img-responsive'/>
    {% endif %}
<p>Image Name : {{ form.instance.contact.name }}</p>
{% if form.instance.contents %}
Contents
<ul>
    {% for item in form.instance.get_content %}
    <li>{{item}}</li>
    {% endfor%}
</ul>
{% endif %}

{% if form.instance.excludes %}
Excludes
<ul>
    {% for item in form.instance.get_excludes %}
    <li>{{item}}</li>
    {% endfor%}
</ul>
{% endif %}

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

django11python3/src/facescan/templates/facescan/item_detail.html
{% extends "base.html" %}

{% block head_title %} Images Detail || {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ object.name }}</h1>
    <img src='{{ instance.image.url }}' class='img-responsive'/>
    <p>Image Name : {{ object.contact.name }}</p>
    {% if object.contents %}
    Contents
    <ul>
        {% for item in object.get_content %}
        <li>{{item}}</li>
        {% endfor%}
    </ul>
    {% endif %}

    {% if object.excludes %}
    Excludes
    <ul>
        {% for item in object.get_excludes %}
        <li>{{item}}</li>
        {% endfor%}
    </ul>
    {% endif %}
</div>

{% endblock %}

django11python3/src/facescan/templates/facescan/item_list.html
{% extends "base.html" %}

{% block head_title %} Images || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Images: <small><a href='{% url "facescan:create" %}'>Add</a></small></h1>
<ul>
    {% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
        {% if obj.image %}
            <img src='{{ obj.image.url }}' class='img-responsive'/>
        {% endif %}
        {% if obj.contents %}
        Contents
        <ul>
            {% for item in obj.get_content %}
            <li>{{item}}</li>
            {% endfor%}
        </ul>
        {% endif %}

        {% if obj.excludes %}
        Excludes
        <ul>
            {% for item in obj.get_excludes %}
            <li>{{item}}</li>
            {% endfor%}
        </ul>
        {% endif %}

    </li>
    {% empty %}
        <li><a href='{% url "facescan:create" %}'>Add New Image</a></li>
    {% endfor %}
</ul>

{% endblock %}

django11python3/src/menu/templates/menu/contactdetails_detail.html
{% extends "base.html" %}

{% block head_title %} Contacts || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ object.name}}</h1>
<p>{{ object.relationship }}</p>

{% endblock %}

django11python3/src/menu/templates/menu/contactdetails_list.html
{% extends "base.html" %}

{% block head_title %} Menu || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>My Contacts <small><a href='{% url "menu:create" %}'>Add new contact</a> </small></h1>

<ul>
    {% for obj in object_list %}
    <li>
        <a href='{{ obj.get_absolute_url }}'>{{ obj }}</a><br/>
        {{ obj.relationship }}</li>
    {% empty %}
    <li><a href='{% url "menu:create"%}'>Add One</a></li>


    {% endfor %}
</ul>

{% endblock %}

django11python3/src/menu/templates/menu/detail-update.html
{% extends "base.html" %}

{% block head_title %} {{ form.instance.name }} | Contacts | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
<p>{{ form.instance.relationship }}</p>

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}


{% endblock %}

django11python3/src/profiles/templates/profiles/user.html
{% extends "base.html" %}

{% block head_title %} {{ user.username }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ user.username }}</h1>
<hr/>
{% if contacts %}
{% for rest in contacts %}
    <div class='row'>
    <div class='col-sm-12'>
        <div class='thumbnail'>
            <h4>{{ rest.title }}</h4>
            <p>{{ rest.relationship }}</p>
            <p>
                <b>Images</b>
            <ul>
                {% for item in rest.item_set.all %}
            <li style='margin-bottom: 15px;'><b>{{ item.name }}</b><br/>
                    {{ item.contents }}
                </li>
                {% endfor %}
            </ul>
            </p>
            <hr/>
        </div>
    </div>
    </div>

{% endfor %}
{% endif %}
{% endblock %}

django11python3/src/recognition/templates/recognition/image_detail.html
{% extends "base.html" %}

{% block head_title %} Image list : detail view || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Test image detail view: </h1>
{% endblock %}
<div class='col-sm-6 col-sm-offset-3'>
    {% if object.image %}
    <img src='{{ object.image.url }}' class='img-responsive' />
    {% endif %}
</div>

{% endblock %}

django11python3/src/recognition/templates/recognition/image_list.html
{% extends "base.html" %}

{% block head_title %} Image list : import image || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Test image: </h1>
<ul>
    <img src="{{ id.Image.image.url }}" width="240">


    <!--<form action="{% url 'recognition:upload_pic' %}" method="post" enctype="multipart/form-data">{% csrf_token %}-->

        <!--<p>-->
            <!--<input id="id_image" type="file" class="" name="image">-->
        <!--</p>-->
        <!--<input type="submit" name="submit"/>-->
    <!--</form>-->

  <!--{% if uploaded_file_url %}-->
    <!--<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>-->
  <!--{% endif %}-->
    <!---->
        <!--{% if obj.image %}-->
            <!--<img src='{{ obj.image.url }}' class='img-responsive'/>-->
        <!--{% endif %}-->


</ul>

{% endblock %}

django11python3/src/recognition/templates/recognition/upload_pic.html
{% extends "base.html" %}

{% block head_title %} Import Images || {{ block.super }}{% endblock head_title %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>Import Image </h1>

</div>

{% endblock %}

django11python3/src/templates/base.html
<head>
    <title>{% block head_title %} Memory Assistant {% endblock head_title %}</title>
{% include 'snippets/css.html' %}
</head>
<body>
{% include 'snippets/nav.html' %}

<div class='container'>
{% block content %} {% endblock content %}
</div>
{% include 'snippets/js.html' %}
</body>

django11python3/src/templates/contact.html
{% extends "base.html" %}

{% block head_title %} Contact || {{ block.super }}{% endblock head_title %}


{% block content %}
<h1>Contact</h1>
<ul>
    {% for obj in object_list %}
    <li>{{ obj.name }} {{ obj.relationship }}</li>
    {% endfor %}
</ul>

{% endblock %}

django11python3/src/templates/form.html
{% extends "base.html" %}

{% block head_title %}{{ title }} | {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>{{ title }}</h1>

{% include 'snippets/form-snippet.html' %}

{% endblock %}

django11python3/src/templates/home.html
{% extends "base.html" %}

{% block content %}
{{ block.super }}
<h1> Home Page </h1>
<h2> Main Menu </h2>
<p>
    html lines {{ html_var }}
</p>
<p>
    {% if bool_item %}
    Random number is {{ num }}
    {% endif %}
</p>
<p>
    {% for some_item in some_list%}
    {% if some_item|divisibleby:"2" %}
    Even number
    {% endif %}
    {{ some_item }}<br/>
    {% endfor %}
</p>
<p>Some item is {{ some_item }} </p>

{% endblock content %}

django11python3/src/templates/myprofile.html
{% extends "base.html" %}

{% block head_title %} My Profile || {{ block.super }}{% endblock head_title %}


{% block content %}
<h1>My Profile</h1>

{% include 'snippets/sidebar.html' %}

{% endblock %}

django11python3/src/templates/recognition.html
{% extends "base.html" %}

{% block head_title %} Recognition || {{ block.super }}{% endblock head_title %}


{% block content %}
<h1>Recognition</h1>

{% include 'snippets/sidebar.html' %}

{% endblock %}

django11python3/src/templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

django11python3/src/templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
{{ form.errors.non_field_errors }}
{% endif %}
<form method='POST' action='' enctype='multipart/form-data'> {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Save</button>
</form>

django11python3/src/templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

django11python3/src/templates/snippets/nav.html
<div class='container'>
<h1> Memory assistant </h1>
<a href='{% url "home" %}'> Home</a></br>
<a href='{% url "myprofile" %}'> My Profile</a>
<a href='{% url "recognition:detect" %}'> Recognition-Detect </a></br>
<a href='{% url "recognition:train" %}'> Recognition-Train </a></br>
{% if request.user.is_authenticated %}
<a href='{% url "menu:list" %}'> Contacts </a>
<a href='{% url "facescan:list" %}'> Images </a>
{% endif %}
</div>

django11python3/src/templates/snippets/sidebar.html
<ul>
<li>Item 1</li>
<li>Item 2</li>
</ul>